runtime: nodejs20  # Ensure this matches your installed Node.js version

handlers:
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/.*\..+

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
